### ISSUE TITLE
Binary url downloading is not working

### ISSUE THREAD

**Issue by ahmeedev** [aguilaair/updat#12]
When I call "startUpdate" it gives me an error status "UpdatStatus.error" in the callback. but the URL is working in the browser. I'm using releases of my private repository

**Comment by aguilaair** [comment]
Ther's your problem, then! You are logged in on GH using your browser so the link works. Try opening that same link in Private mode / Incognito, you'll see it won't work.

**Comment by aguilaair** [comment]
I'm going to close the issue, let me know if you need any help! The easiest way to handle this if you just have a public repo with your releases.
