### ISSUE TITLE
CloseOnInstall does not work

### ISSUE THREAD

**Issue by 89pleasure** [aguilaair/updat#13]
Hello! Thank you for the nice library. It looks nice so far and I still need to play around a little bit.
The CloseOnInstall function does not work when used with bool true.
I do not get any errors or exceptions, just does not do anything. 

Is there any tutorial or example on how to implement an automatic restart and replace of the application?

Greetings

**Comment by aguilaair** [comment]
Hey! Thank you!

Could you check https://github.com/aguilaair/updat/issues/9, it should have been fixed with the latest version.

Let me know if you still have issues and I'll take a look

**Comment by aguilaair** [comment]
That's probably it! That is correct, give it an app image, dmg, msi, msix, exe and it will run it.

Regarding the chip placement when using the manager, I do not think it is customizable right now. Feel free to open another issue about it or simply copy the source code for the widget and change whatever you need. It is really just a wrapper around the other components.

**Comment by 89pleasure** [comment]
Alright, thanks
