### ISSUE TITLE
allow manager to run on non-desktop platforms

### ISSUE THREAD

**Issue by marwenbk** [aguilaair/updat#14]
run on Ipad with IpadOS 16.5,
got MissingPluginException (MissingPluginException(No implementation found for method setPreventClose on channel window_manager))

**Comment by aguilaair** [comment]
This is designed for desktop applications and as such does not have mobile support, I can see wether I can add some sort of conditional import to at least make sure it does not error out and simply ignores it.

**Comment by marwenbk** [comment]
Thank you for the clarification, however on the pub.dev the plugin mention support for all the platform, and i had found example for android in the project example, but on android i got
UnsupportedError (Unsupported operation: getDownloadsPath is not supported on Android)

**Comment by aguilaair** [comment]
Interesting! I'll make a fix to the package so it can run on mobile

**Comment by aguilaair** [comment]
1.3.1 should solve the issue!
