### ISSUE TITLE
Improve UpdatGlobalOptions docs

### ISSUE THREAD

**Issue by marwenbk** [aguilaair/updat#15]
There is no documentation for UpdatGlobalOptions usages to add header to access private repository for example,

please note we need to make "Accept": "application/octet-stream", header if we want to download the asset with github rest api

**Comment by aguilaair** [comment]
is this not it https://github.com/aguilaair/updat#advanced-usage?

**Comment by aguilaair** [comment]
Gotcha makes sense. Feel free to create a PR to improve the doc clarity and/or add it to the example!

**Comment by aguilaair** [comment]
Added!
