### ISSUE TITLE
How to use this package with inno setup 

### ISSUE THREAD

**Issue by vinodh013** [aguilaair/updat#17]
I need help understanding how the process of updating software will work

1. If I create an exe file - v 1.0 using inno setup, and release it to GitHub.
2. Then update the new version and release it on GitHub  with v - 2.0

Then how the download and installation process will work  for a user can you help  me to understand that 
Thank you in advance.

**Comment by aguilaair** [comment]
3 - Then by checking `getLatestVersion` it would return `2.0.0`, which is semantically higher.
4 - Runs `getBinaryUrl` to get the download link, once you return it, it will start downloading the file based on `appName`
5 - This step now depends on what you are doing, but basically it will wait until you tell it to open the installer and then it will do so.

**Comment by aguilaair** [comment]
Please check: https://github.com/aguilaair/updat/wiki/How-to-integrate-Updat

**Comment by marwenbk** [comment]
@vinodh013 you should .msix not .exe
Updat is not a fully automated update solution for your flutter apps. Updat is not an installer, we recommend you use a DMG for mac, AppImage for Linux, and MSIX for Windows.

**Comment by aguilaair** [comment]
.exe should be fine too, as long as it is an installer. I just recommend using MSIX :)
