### ISSUE TITLE
Fluent UI compatibility

### ISSUE THREAD

**Issue by BilPat** [aguilaair/updat#18]
I'm currently using the fluent_ui package (4.6.2). Is there a way to integrate UpdatWindowManager for fluent_ui users? Wrapping Fluent UI in MaterialApp works, but leads to frequent null check errors.

Thanks in advance! Your package is awesome!

**Comment by BilPat** [comment]
Consider the issue closed - For people who struggle with the implementation in FluentUI like me, you have to wrap your NavigationView widget inside UpdatWindowManager. This resulted in the desired behaviour.

Like this:

````
@override
  Widget build(BuildContext context) {
    return FluentApp(
        theme: FluentThemeData(
            scaffoldBackgroundColor: Colors.white,
            accentColor: Colors.blue,
            iconTheme: const IconThemeData(size: 24)),
        home: UpdatWindowManager(
          getLatestVersion: () async {
            return "1.0.0";
          },
          getBinaryUrl: (version) async {
            return "https://getcomposer.org/Composer-Setup.exe";
          },
          appName:
              "Updat Example",

          updateChipBuilder: floatingExtendedChipWithSilentDownload,
          currentVersion: '0.0.1',
          callback: (status) {
            print(status);
          },

          child: NavigationView(//and so on
````

I think it might help if you update your readme accordingly, I'd imagine that fluent_ui will gain popularity if more people develop windows apps with flutter.

Thanks again for your great package!

**Comment by aguilaair** [comment]
I'll add a note to the Readme for the next release!

**Comment by aguilaair** [comment]
Also, if you want to contribute fluent_ui chips and dialogs I would be happy to add them to a community repository or similar
