### ISSUE TITLE
is there mac os preview?

### ISSUE THREAD

**Issue by hatemragab** [aguilaair/updat#2]
is this package support macOS update?

**Comment by aguilaair** [comment]
Hey! It does, you will have to build the dmg, but this will work on macOS (especially since the 1.2.0 release)

**Comment by aguilaair** [comment]
https://github.com/aguilaair/updat/wiki/How-to-integrate-Updat

**Comment by hatemragab** [comment]
Thank for replying,
I was wondering how the update done for mac users and what if use put the dmg in his /Applications how to delete the old dmg and replace it with the new dmg

**Comment by aguilaair** [comment]
When Updat launches the DMG, the user has to drag it into the application's folder and click on replace, and it will be done automatically.

`pkg` files may also be used for unattended setups.

Please note DMGs are not moved to /Applications the `.app` is though
