### ISSUE TITLE
Is there any way to view detailed error?

### ISSUE THREAD

**Issue by mukhtharcm** [aguilaair/updat#20]
The title.

Is there any way to view detailed error apart from the updatStatus.error?

My update is downloading then suddenly it's error. Can't figure whats going on :)

**Comment by aguilaair** [comment]
Hey! Your best bet is going to be jumping into the download logic on the package and adding a breakpoint, or just enabling breakpoints at "All Exceptions".

**Comment by mukhtharcm** [comment]
Thank you! I haven't thought about that!
I tried editing the file directly but it didn't do anything.
Thank you for this :)

**Comment by aguilaair** [comment]
Of course! Let me know if there is something that could be improved in the package once you figure out what's wrong :D
